<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

  public function findLast($nb = 10){
    return $this->createQueryBuilder('a')
                ->OrderBy('a.date','DESC')
                ->setMaxResults($nb)
                ->getQuery()
                ->getResult()
                ;
  }
  public function getPage($page = 1, $nb = 10, $query){
    $queryBuilder = $this->createQueryBuilder('a')
                ->OrderBy('a.date','DESC')
                ->setMaxResults($nb)
                ->setOffset($nb * ($page - 1));
    if (!empty(array_filter($query))){
      if ($name = $query['name']){
        $queryBuilder->Where('a.name LIKE \'%:name%\'')
                     ->setParameter('name', $name)
                     ;
      }
      if ($tag = $query['tag']){
        $queryBuilder->leftJoin('a.tags', 't')
                     ->Where('t.name LIKE \'%:tag%\'')
                     ->setParameter('tag', $tag)
                     ;
      }
    }
    $query->getQuery()
          ->getResult()
          ;
  }

}
