<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
  public function getCommentCount($id){
      return $this->createQueryBuilder('c')
                  ->select('count(c.id)')
                  ->where('c.article = :id')
                  ->setParameter(':id', $id)
                  ->getQuery()
                  ->getSingleScalarResult();
  }
}
