# To get started with security, check out the documentation:
# http://symfony.com/doc/current/security.html
security:

    # http://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        in_memory:
            memory:
                users:
                    sebb:
                        password: $2y$12$.BHSZqAPZZrsUZz1oD.J7uJXjxln93Sw3xt0D2VW/OWBZ0fcJPLiS
                        roles: 'ROLE_ADMIN'
    encoders:
        Symfony\Component\Security\Core\User\User:
            algorithm: bcrypt
            cost: 12

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            form_login:
                login_path: /administration/login
                check_path: /administration/login
            logout:
              path: /logout
              target: /article
    access_control:
        - { path: ^/administration/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        # require ROLE_ADMIN for /administration*
        - { path: ^/administration, roles: ROLE_ADMIN }
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
