# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
services:
    app.article_listener:
        class: AppBundle\EventListener\ArticleListener
        arguments: ['@security.token_storage']
        tags:
            - { name: doctrine.event_listener,  event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
    app.form.type.comment:
      class: AppBundle\Form\CommentType
      arguments: ["@doctrine.orm.entity_manager"]
      tags:
          - { name: form.type }
    app.twig_function:
        class: AppBundle\Twig\AppExtension
        public: true
        tags:
            - { name: twig.extension }
        arguments: ['@doctrine.orm.entity_manager']
